//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajdataEdit.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs_zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MajdataEdit.Langs.Langs.zh-CN", typeof(Langs_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要关闭View吗？.
        /// </summary>
        public static string AskCloseView {
            get {
                return ResourceManager.GetString("AskCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 即将开始渲染，将导出视频到谱面目录。
        ///请注意在渲染时不要改变Viewer窗口大小。
        ///现在按Viewer右上角&lt; &gt;可以设置渲染分辨率。
        ///请保证分辨率宽度为偶数。
        ///按确定开始渲染。.
        /// </summary>
        public static string AskRender {
            get {
                return ResourceManager.GetString("AskRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未保存，要保存吗？.
        /// </summary>
        public static string AskSave {
            get {
                return ResourceManager.GetString("AskSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动检查更新(启动时).
        /// </summary>
        public static string AutoCheckUpdate {
            get {
                return ResourceManager.GetString("AutoCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动保存（秒）.
        /// </summary>
        public static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (你可以在编辑器设置中禁用自动检查更新功能).
        /// </summary>
        public static string AutoUpdateCheckTip {
            get {
                return ResourceManager.GetString("AutoUpdateCheckTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM Tap.
        /// </summary>
        public static string BPMtap {
            get {
                return ResourceManager.GetString("BPMtap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景亮度.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 谱面刷新延迟(毫秒).
        /// </summary>
        public static string ChartRefreshDelay {
            get {
                return ResourceManager.GetString("ChartRefreshDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测完毕, 共发现{0}个多押无理，{1}个撞尾无理。您可在 检测结果 窗口中查看
        ///请注意：谱面无理检测提供的意见并不一定准确，结果仅供参考。.
        /// </summary>
        public static string CheckDone1 {
            get {
                return ResourceManager.GetString("CheckDone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测完毕, 共发现{0}个撞尾无理。您可在 检测结果 窗口中查看
        ///请注意：谱面无理检测提供的意见并不一定准确，结果仅供参考。.
        /// </summary>
        public static string CheckDone2 {
            get {
                return ResourceManager.GetString("CheckDone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo显示.
        /// </summary>
        public static string ComboDisplay {
            get {
                return ResourceManager.GetString("ComboDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测结果.
        /// </summary>
        public static string DetResult {
            get {
                return ResourceManager.GetString("DetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 难度.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string EditorLanguage {
            get {
                return ResourceManager.GetString("EditorLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑器设置.
        /// </summary>
        public static string EditorSetting {
            get {
                return ResourceManager.GetString("EditorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出视频.
        /// </summary>
        public static string ExportVideo {
            get {
                return ResourceManager.GetString("ExportVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        public static string FIles {
            get {
                return ResourceManager.GetString("FIles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找与替换.
        /// </summary>
        public static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找下一个.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双击可转到对应错误行.
        /// </summary>
        public static string GotoLineTooltip {
            get {
                return ResourceManager.GetString("GotoLineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp3中有封面。要一并载入（并替换当前）封面吗？.
        /// </summary>
        public static string IsOverridePicture {
            get {
                return ResourceManager.GetString("IsOverridePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从其他mp3中读取.
        /// </summary>
        public static string LoadFromFile {
            get {
                return ResourceManager.GetString("LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从track.mp3中读取.
        /// </summary>
        public static string LoadFromTrack {
            get {
                return ResourceManager.GetString("LoadFromTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maidata.txt已存在.
        /// </summary>
        public static string MaidataExist {
            get {
                return ResourceManager.GetString("MaidataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 谱面信息.
        /// </summary>
        public static string MapInfo {
            get {
                return ResourceManager.GetString("MapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 谱面无理检测.
        /// </summary>
        public static string MapMuriDetc {
            get {
                return ResourceManager.GetString("MapMuriDetc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180°翻转选择.
        /// </summary>
        public static string Mirror180 {
            get {
                return ResourceManager.GetString("Mirror180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45°顺时针旋转选择.
        /// </summary>
        public static string Mirror45 {
            get {
                return ResourceManager.GetString("Mirror45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45°逆时针旋转选择.
        /// </summary>
        public static string MirrorCcw45 {
            get {
                return ResourceManager.GetString("MirrorCcw45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左右翻转选择.
        /// </summary>
        public static string MirrorLR {
            get {
                return ResourceManager.GetString("MirrorLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上下翻转选择.
        /// </summary>
        public static string MirrorUD {
            get {
                return ResourceManager.GetString("MirrorUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启多押检测.
        /// </summary>
        public static string MultNoteEnable {
            get {
                return ResourceManager.GetString("MultNoteEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [多押无理] .
        /// </summary>
        public static string MultNoteError1 {
            get {
                return ResourceManager.GetString("MultNoteError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可能形成了{0}押.
        /// </summary>
        public static string MultNoteError2 {
            get {
                return ResourceManager.GetString("MultNoteError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测三押或三押以上的多押无理
        ///如果您的谱面允许多押存在 如协力宴谱 您可以禁用这个选项.
        /// </summary>
        public static string MultNoteTooltip {
            get {
                return ResourceManager.GetString("MultNoteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查到新版本 {0}
        ///(当前版本为 {1})
        ///
        ///是否前往下载？.
        /// </summary>
        public static string NewVersionDetected {
            get {
                return ResourceManager.GetString("NewVersionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请完成编辑器初始设置.
        /// </summary>
        public static string NoEditorSetting {
            get {
                return ResourceManager.GetString("NoEditorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到maidata.txt.
        /// </summary>
        public static string NoMaidata_txt {
            get {
                return ResourceManager.GetString("NoMaidata_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您已经是最新版本了，无需更新.
        /// </summary>
        public static string NoNewVersion {
            get {
                return ResourceManager.GetString("NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请存入track.mp3.
        /// </summary>
        public static string NoTrack_mp3 {
            get {
                return ResourceManager.GetString("NoTrack_mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏移.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 覆盖模式.
        /// </summary>
        public static string OverwriteMode {
            get {
                return ResourceManager.GetString("OverwriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 覆盖模式下，输入的文字将替换光标后的内容。
        ///按Insert键回到标准模式。.
        /// </summary>
        public static string OverwriteModeTooltip {
            get {
                return ResourceManager.GetString("OverwriteModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 播放速度.
        /// </summary>
        public static string PlayBackSpeed {
            get {
                return ResourceManager.GetString("PlayBackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确保你打开了MajdataView且端口（8013）畅通.
        /// </summary>
        public static string PortClear {
            get {
                return ResourceManager.GetString("PortClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制模式.
        /// </summary>
        public static string RecMode {
            get {
                return ResourceManager.GetString("RecMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从头开始播放，并带有动画.
        /// </summary>
        public static string RecordModeDiscrp {
            get {
                return ResourceManager.GetString("RecordModeDiscrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新对准编辑器窗口.
        /// </summary>
        public static string RemapViewer {
            get {
                return ResourceManager.GetString("RemapViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染模式.
        /// </summary>
        public static string RenderMode {
            get {
                return ResourceManager.GetString("RenderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 硬件渲染.
        /// </summary>
        public static string RenderModeHW {
            get {
                return ResourceManager.GetString("RenderModeHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件渲染.
        /// </summary>
        public static string RenderModeSW {
            get {
                return ResourceManager.GetString("RenderModeSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 替换下一个.
        /// </summary>
        public static string ReplaceNext {
            get {
                return ResourceManager.GetString("ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络请求失败，请检查网络后重试.
        /// </summary>
        public static string RequestFail {
            get {
                return ResourceManager.GetString("RequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存为.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请设置艺术家.
        /// </summary>
        public static string SetArtist {
            get {
                return ResourceManager.GetString("SetArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将当前音量设为默认.
        /// </summary>
        public static string SetDefaultVolume {
            get {
                return ResourceManager.GetString("SetDefaultVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请设置做谱人.
        /// </summary>
        public static string SetDes {
            get {
                return ResourceManager.GetString("SetDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请设置标题.
        /// </summary>
        public static string SetTitle {
            get {
                return ResourceManager.GetString("SetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置音量到默认值.
        /// </summary>
        public static string SetToDefaultVolume {
            get {
                return ResourceManager.GetString("SetToDefaultVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置成功，之后新建的新谱面将会沿用目前的音量设置.
        /// </summary>
        public static string SetVolumeDefaultSuccess {
            get {
                return ResourceManager.GetString("SetVolumeDefaultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimaiWiki.
        /// </summary>
        public static string SimaiWiki {
            get {
                return ResourceManager.GetString("SimaiWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide撞尾检测精度必须是个数字! 请检查您输入是否有误, 如误输入了空格..
        /// </summary>
        public static string SlideAccInputError {
            get {
                return ResourceManager.GetString("SlideAccInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide撞尾检测精度:.
        /// </summary>
        public static string SlideAccuracy {
            get {
                return ResourceManager.GetString("SlideAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [撞尾无理] &quot;{0}&quot;({1}L,{2}C)可能会撞上&quot;{3}&quot;({4}L,{5}C) 二者间隔{6}ms.
        /// </summary>
        public static string SlideError {
            get {
                return ResourceManager.GetString("SlideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撞尾无理：当slide经过tap（A区）时，这个tap可能会被误触发
        ///检查撞尾无理的精度，单位是秒。
        ///建议您不要设置低于0.15的值，因为0.15秒是GOOD判定的区间，
        ///如果小于这个值，必定无理的撞尾就无法被检测出来。
        ///您可以设置略高于0.15的值，如0.2，此时容易蹭尾的配置也会被
        ///检测出来.
        /// </summary>
        public static string SlideTooltip {
            get {
                return ResourceManager.GetString("SlideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在以软件渲染模式运行.
        /// </summary>
        public static string SoftRender {
            get {
                return ResourceManager.GetString("SoftRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染进程错误！
        ///请尝试通过强制软件渲染使用本软件
        ///（通过双击文件夹中的 &quot;强制软件渲染.bat&quot;启动本程序）.
        /// </summary>
        public static string SoftRenderError {
            get {
                return ResourceManager.GetString("SoftRenderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请在 设置-&gt;编辑器设置 中调整.
        /// </summary>
        public static string SpeedSettingTooltip {
            get {
                return ResourceManager.GetString("SpeedSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始检测.
        /// </summary>
        public static string StartCheck {
            get {
                return ResourceManager.GetString("StartCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [语法错误] &quot;{0}&quot;({1}L,{2}C)解析失败，可能存在语法错误.
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本跟随.
        /// </summary>
        public static string TextFollow {
            get {
                return ResourceManager.GetString("TextFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch速度.
        /// </summary>
        public static string TouchSpeed {
            get {
                return ResourceManager.GetString("TouchSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (未保存).
        /// </summary>
        public static string Unsaved {
            get {
                return ResourceManager.GetString("Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音量.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可能不支持非44100Hz的mp3文件.
        /// </summary>
        public static string Warn44100Hz {
            get {
                return ResourceManager.GetString("Warn44100Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这是什么.
        /// </summary>
        public static string WhatsThis {
            get {
                return ResourceManager.GetString("WhatsThis", resourceCulture);
            }
        }
    }
}
