//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajdataEdit.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs_ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MajdataEdit.Langs.Langs.ja", typeof(Langs_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewを閉しますか？.
        /// </summary>
        public static string AskCloseView {
            get {
                return ResourceManager.GetString("AskCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 譜面動画は譜面フォルダにエクスポートされます。
        ///レンダリング中にViewerのサイズを変更しないでください。
        ///ただし、[&lt;&gt;] ボタンを使用して解像度を変更できます。
        ///幅が偶数であることを確認してください。
        ///[OK] をクリックして生成を開始します。.
        /// </summary>
        public static string AskRender {
            get {
                return ResourceManager.GetString("AskRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存されていませんが、保存しますか？.
        /// </summary>
        public static string AskSave {
            get {
                return ResourceManager.GetString("AskSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Check Update (when start).
        /// </summary>
        public static string AutoCheckUpdate {
            get {
                return ResourceManager.GetString("AutoCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オートセーブ （秒）.
        /// </summary>
        public static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (You can disabled AutoCheckUpdate in Editor Setting Panel).
        /// </summary>
        public static string AutoUpdateCheckTip {
            get {
                return ResourceManager.GetString("AutoUpdateCheckTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM Tap.
        /// </summary>
        public static string BPMtap {
            get {
                return ResourceManager.GetString("BPMtap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明るさ.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Refresh Delay(ms).
        /// </summary>
        public static string ChartRefreshDelay {
            get {
                return ResourceManager.GetString("ChartRefreshDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Finished, {0} Multi-Notes Error，{1} Slide-Tap Error. You can get more information in the Result Window.
        ///PS: The results is not 100% accurate..
        /// </summary>
        public static string CheckDone1 {
            get {
                return ResourceManager.GetString("CheckDone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Finished, {0} Slide-Tap Error. You can get more information in the Result Window.
        ///PS: The results is not 100% accurate..
        /// </summary>
        public static string CheckDone2 {
            get {
                return ResourceManager.GetString("CheckDone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckUpdate.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMBO表示.
        /// </summary>
        public static string ComboDisplay {
            get {
                return ResourceManager.GetString("ComboDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 結果.
        /// </summary>
        public static string DetResult {
            get {
                return ResourceManager.GetString("DetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語.
        /// </summary>
        public static string EditorLanguage {
            get {
                return ResourceManager.GetString("EditorLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エディタの設定.
        /// </summary>
        public static string EditorSetting {
            get {
                return ResourceManager.GetString("EditorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 譜面動画を生成.
        /// </summary>
        public static string ExportVideo {
            get {
                return ResourceManager.GetString("ExportVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル.
        /// </summary>
        public static string FIles {
            get {
                return ResourceManager.GetString("FIles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索と置換.
        /// </summary>
        public static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次を検索.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブルクリックしてエラー行にジャンプできます.
        /// </summary>
        public static string GotoLineTooltip {
            get {
                return ResourceManager.GetString("GotoLineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メッセージ.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3ファイルに画像がいます。利用しますか？.
        /// </summary>
        public static string IsOverridePicture {
            get {
                return ResourceManager.GetString("IsOverridePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のmp3から読み込む.
        /// </summary>
        public static string LoadFromFile {
            get {
                return ResourceManager.GetString("LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.mp3から読み込む.
        /// </summary>
        public static string LoadFromTrack {
            get {
                return ResourceManager.GetString("LoadFromTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maidata.txtがすでに存在しています.
        /// </summary>
        public static string MaidataExist {
            get {
                return ResourceManager.GetString("MaidataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 譜面情報.
        /// </summary>
        public static string MapInfo {
            get {
                return ResourceManager.GetString("MapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無理押しチェッカー.
        /// </summary>
        public static string MapMuriDetc {
            get {
                return ResourceManager.GetString("MapMuriDetc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180°反転.
        /// </summary>
        public static string Mirror180 {
            get {
                return ResourceManager.GetString("Mirror180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45°回転（時計回り）.
        /// </summary>
        public static string Mirror45 {
            get {
                return ResourceManager.GetString("Mirror45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45°回転（反時計回り）.
        /// </summary>
        public static string MirrorCcw45 {
            get {
                return ResourceManager.GetString("MirrorCcw45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平方向に反転.
        /// </summary>
        public static string MirrorLR {
            get {
                return ResourceManager.GetString("MirrorLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直方向に反転.
        /// </summary>
        public static string MirrorUD {
            get {
                return ResourceManager.GetString("MirrorUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Notes Detection.
        /// </summary>
        public static string MultNoteEnable {
            get {
                return ResourceManager.GetString("MultNoteEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MultiNotesError].
        /// </summary>
        public static string MultNoteError1 {
            get {
                return ResourceManager.GetString("MultNoteError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to may be appear in the same time.({0} Notes).
        /// </summary>
        public static string MultNoteError2 {
            get {
                return ResourceManager.GetString("MultNoteError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will warn you if there is more than 3 notes appear in the same time.
        ///If your map allow this situation, e.g. UTAGE map, you can disable this option..
        /// </summary>
        public static string MultNoteTooltip {
            get {
                return ResourceManager.GetString("MultNoteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version detected: {0}
        ///(your current version: {1})
        ///
        ///Open Browser to download latest update of Majdata?.
        /// </summary>
        public static string NewVersionDetected {
            get {
                return ResourceManager.GetString("NewVersionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エディタの初期設定を完了してください.
        /// </summary>
        public static string NoEditorSetting {
            get {
                return ResourceManager.GetString("NoEditorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maidata.txtが存在することを確認してください.
        /// </summary>
        public static string NoMaidata_txt {
            get {
                return ResourceManager.GetString("NoMaidata_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Majdata doesn&apos;t need to update..
        /// </summary>
        public static string NoNewVersion {
            get {
                return ResourceManager.GetString("NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.mp3が存在することを確認してください.
        /// </summary>
        public static string NoTrack_mp3 {
            get {
                return ResourceManager.GetString("NoTrack_mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ｵﾌｾｯﾄ.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開く.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Mode.
        /// </summary>
        public static string OverwriteMode {
            get {
                return ResourceManager.GetString("OverwriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite mode allows you to replace text as you type.
        ///Press the Insert key to switch back to normal mode..
        /// </summary>
        public static string OverwriteModeTooltip {
            get {
                return ResourceManager.GetString("OverwriteModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再生速度.
        /// </summary>
        public static string PlayBackSpeed {
            get {
                return ResourceManager.GetString("PlayBackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MajdataViewが開いていて、ポート（8013）が開いていることを確認してください。.
        /// </summary>
        public static string PortClear {
            get {
                return ResourceManager.GetString("PortClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 録画モード.
        /// </summary>
        public static string RecMode {
            get {
                return ResourceManager.GetString("RecMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to はちめからプレイ（info/AP付）.
        /// </summary>
        public static string RecordModeDiscrp {
            get {
                return ResourceManager.GetString("RecordModeDiscrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewerを揃える.
        /// </summary>
        public static string RemapViewer {
            get {
                return ResourceManager.GetString("RemapViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レンダリング モード.
        /// </summary>
        public static string RenderMode {
            get {
                return ResourceManager.GetString("RenderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハードウェア.
        /// </summary>
        public static string RenderModeHW {
            get {
                return ResourceManager.GetString("RenderModeHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソフトウェア.
        /// </summary>
        public static string RenderModeSW {
            get {
                return ResourceManager.GetString("RenderModeSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次を置換.
        /// </summary>
        public static string ReplaceNext {
            get {
                return ResourceManager.GetString("ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet request fail, please check your internet connection..
        /// </summary>
        public static string RequestFail {
            get {
                return ResourceManager.GetString("RequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上書き保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前を付けて保存.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artistを設定.
        /// </summary>
        public static string SetArtist {
            get {
                return ResourceManager.GetString("SetArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在の音量をデフォルトに設定.
        /// </summary>
        public static string SetDefaultVolume {
            get {
                return ResourceManager.GetString("SetDefaultVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note designerを設定.
        /// </summary>
        public static string SetDes {
            get {
                return ResourceManager.GetString("SetDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトルを設定.
        /// </summary>
        public static string SetTitle {
            get {
                return ResourceManager.GetString("SetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Volume as Default Setting.
        /// </summary>
        public static string SetToDefaultVolume {
            get {
                return ResourceManager.GetString("SetToDefaultVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Your new chart will use these volume setting as default..
        /// </summary>
        public static string SetVolumeDefaultSuccess {
            get {
                return ResourceManager.GetString("SetVolumeDefaultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimaiWiki.
        /// </summary>
        public static string SimaiWiki {
            get {
                return ResourceManager.GetString("SimaiWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Detection Accuracy must be a number! Please check your input and delete unnecessary charactors like space..
        /// </summary>
        public static string SlideAccInputError {
            get {
                return ResourceManager.GetString("SlideAccInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide-Tap Detection Acc:.
        /// </summary>
        public static string SlideAccuracy {
            get {
                return ResourceManager.GetString("SlideAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SlideTapError] &quot;{0}&quot;({1}L,{2}C) may obstructs &quot;{3}&quot;({4}L,{5}C). Interval:{6}ms.
        /// </summary>
        public static string SlideError {
            get {
                return ResourceManager.GetString("SlideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide-Tap Error: when a SLIDE pass a TAP in &quot;A Area&quot;, it may 
        ///trigger this TAP unexpected.
        ///The accuracy of detection on Slide-Tap Error. Unit: second.
        ///Please DO NOT enter a value less than 0.15, or some of
        ///Impossible Notes will not be found out.
        ///If you wanna an excellent map, you can set the accuracy to
        ///0.2 or higher..
        /// </summary>
        public static string SlideTooltip {
            get {
                return ResourceManager.GetString("SlideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソフトウェア・レンダリング・モードで動作.
        /// </summary>
        public static string SoftRender {
            get {
                return ResourceManager.GetString("SoftRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Thread Failure！
        ///Please run the MajdatEdit by &quot;强制软件渲染.bat&quot; in the folder. This may solve the problem..
        /// </summary>
        public static string SoftRenderError {
            get {
                return ResourceManager.GetString("SoftRenderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change these settings, go to &quot;Setting-&gt;Editor Setting&quot;..
        /// </summary>
        public static string SpeedSettingTooltip {
            get {
                return ResourceManager.GetString("SpeedSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検査.
        /// </summary>
        public static string StartCheck {
            get {
                return ResourceManager.GetString("StartCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SyntaxError] &quot;{0}&quot;({1}L,{2}C) fail to analyze，may be a syntax error here..
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 譜面フォロー.
        /// </summary>
        public static string TextFollow {
            get {
                return ResourceManager.GetString("TextFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツール.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タッチ速度.
        /// </summary>
        public static string TouchSpeed {
            get {
                return ResourceManager.GetString("TouchSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (保存されていません).
        /// </summary>
        public static string Unsaved {
            get {
                return ResourceManager.GetString("Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音量.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44100Hz以外のmp3ファイルには対応していない場合があります.
        /// </summary>
        public static string Warn44100Hz {
            get {
                return ResourceManager.GetString("Warn44100Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なにこれ.
        /// </summary>
        public static string WhatsThis {
            get {
                return ResourceManager.GetString("WhatsThis", resourceCulture);
            }
        }
    }
}
