//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajdataEdit.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MajdataEdit.Langs.Langs.en-US", typeof(Langs_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Viewer?.
        /// </summary>
        public static string AskCloseView {
            get {
                return ResourceManager.GetString("AskCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video will be exported to the chart folder.
        ///DO NOT CHANGE THE VIEWER WINDOW SIZE DURING THE RENDER.
        ///But you can change the resolution now using the &quot;&lt;&gt;&quot; button.
        ///Please make sure that the width is even number.
        ///Click OK to start render..
        /// </summary>
        public static string AskRender {
            get {
                return ResourceManager.GetString("AskRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not saved. Save now?.
        /// </summary>
        public static string AskSave {
            get {
                return ResourceManager.GetString("AskSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Check Update (when start).
        /// </summary>
        public static string AutoCheckUpdate {
            get {
                return ResourceManager.GetString("AutoCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave (s).
        /// </summary>
        public static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (You can disabled AutoCheckUpdate in Editor Setting Panel).
        /// </summary>
        public static string AutoUpdateCheckTip {
            get {
                return ResourceManager.GetString("AutoUpdateCheckTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM Tap.
        /// </summary>
        public static string BPMtap {
            get {
                return ResourceManager.GetString("BPMtap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Refresh Delay(ms).
        /// </summary>
        public static string ChartRefreshDelay {
            get {
                return ResourceManager.GetString("ChartRefreshDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Finished, {0} Multi-Notes Error，{1} Slide-Tap Error. You can get more information in the Result Window.
        ///PS: The results is not 100% accurate..
        /// </summary>
        public static string CheckDone1 {
            get {
                return ResourceManager.GetString("CheckDone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Finished, {0} Slide-Tap Error. You can get more information in the Result Window.
        ///PS: The results is not 100% accurate..
        /// </summary>
        public static string CheckDone2 {
            get {
                return ResourceManager.GetString("CheckDone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckUpdate.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Display.
        /// </summary>
        public static string ComboDisplay {
            get {
                return ResourceManager.GetString("ComboDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string DetResult {
            get {
                return ResourceManager.GetString("DetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string EditorLanguage {
            get {
                return ResourceManager.GetString("EditorLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Setting.
        /// </summary>
        public static string EditorSetting {
            get {
                return ResourceManager.GetString("EditorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Video.
        /// </summary>
        public static string ExportVideo {
            get {
                return ResourceManager.GetString("ExportVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FIles {
            get {
                return ResourceManager.GetString("FIles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to jump to the error line..
        /// </summary>
        public static string GotoLineTooltip {
            get {
                return ResourceManager.GetString("GotoLineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a cover picture in mp3 file. Do you want to use it?.
        /// </summary>
        public static string IsOverridePicture {
            get {
                return ResourceManager.GetString("IsOverridePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From other mp3 file.
        /// </summary>
        public static string LoadFromFile {
            get {
                return ResourceManager.GetString("LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load meta from track.
        /// </summary>
        public static string LoadFromTrack {
            get {
                return ResourceManager.GetString("LoadFromTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maidata.txt already exist..
        /// </summary>
        public static string MaidataExist {
            get {
                return ResourceManager.GetString("MaidataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map info.
        /// </summary>
        public static string MapInfo {
            get {
                return ResourceManager.GetString("MapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Impossible Notes Detection.
        /// </summary>
        public static string MapMuriDetc {
            get {
                return ResourceManager.GetString("MapMuriDetc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180° Mirror Selection.
        /// </summary>
        public static string Mirror180 {
            get {
                return ResourceManager.GetString("Mirror180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45° Rotate Selection.
        /// </summary>
        public static string Mirror45 {
            get {
                return ResourceManager.GetString("Mirror45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45° (CCW) Rotate Selection.
        /// </summary>
        public static string MirrorCcw45 {
            get {
                return ResourceManager.GetString("MirrorCcw45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror L-R Selection.
        /// </summary>
        public static string MirrorLR {
            get {
                return ResourceManager.GetString("MirrorLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror U-D Selection.
        /// </summary>
        public static string MirrorUD {
            get {
                return ResourceManager.GetString("MirrorUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Notes Detection.
        /// </summary>
        public static string MultNoteEnable {
            get {
                return ResourceManager.GetString("MultNoteEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MultiNotesError] .
        /// </summary>
        public static string MultNoteError1 {
            get {
                return ResourceManager.GetString("MultNoteError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  may appear in the same time.({0} Notes).
        /// </summary>
        public static string MultNoteError2 {
            get {
                return ResourceManager.GetString("MultNoteError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will warn you if there are more than 3 notes appearing at the same time.
        ///You can get this option disabled if this situation is allowed to happen, e.g. UTAGE map..
        /// </summary>
        public static string MultNoteTooltip {
            get {
                return ResourceManager.GetString("MultNoteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version detected: {0}
        ///(your current version: {1})
        ///
        ///Open Browser to download latest update of Majdata?.
        /// </summary>
        public static string NewVersionDetected {
            get {
                return ResourceManager.GetString("NewVersionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the initial setup of the editor..
        /// </summary>
        public static string NoEditorSetting {
            get {
                return ResourceManager.GetString("NoEditorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure maidata.txt exists..
        /// </summary>
        public static string NoMaidata_txt {
            get {
                return ResourceManager.GetString("NoMaidata_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Majdata doesn&apos;t need to update..
        /// </summary>
        public static string NoNewVersion {
            get {
                return ResourceManager.GetString("NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure track.mp3 exists..
        /// </summary>
        public static string NoTrack_mp3 {
            get {
                return ResourceManager.GetString("NoTrack_mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite mode.
        /// </summary>
        public static string OverwriteMode {
            get {
                return ResourceManager.GetString("OverwriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite mode allows you to replace text as you type.
        ///Press the Insert key to switch back to normal mode..
        /// </summary>
        public static string OverwriteModeTooltip {
            get {
                return ResourceManager.GetString("OverwriteModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayBackSpeed.
        /// </summary>
        public static string PlayBackSpeed {
            get {
                return ResourceManager.GetString("PlayBackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure MajdataView is open and port 8013 is available.
        /// </summary>
        public static string PortClear {
            get {
                return ResourceManager.GetString("PortClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record mode.
        /// </summary>
        public static string RecMode {
            get {
                return ResourceManager.GetString("RecMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play from start with animation.
        /// </summary>
        public static string RecordModeDiscrp {
            get {
                return ResourceManager.GetString("RecordModeDiscrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-align viewer.
        /// </summary>
        public static string RemapViewer {
            get {
                return ResourceManager.GetString("RemapViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering Mode.
        /// </summary>
        public static string RenderMode {
            get {
                return ResourceManager.GetString("RenderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string RenderModeHW {
            get {
                return ResourceManager.GetString("RenderModeHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string RenderModeSW {
            get {
                return ResourceManager.GetString("RenderModeSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Next.
        /// </summary>
        public static string ReplaceNext {
            get {
                return ResourceManager.GetString("ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet request fail, please check your internet connection..
        /// </summary>
        public static string RequestFail {
            get {
                return ResourceManager.GetString("RequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAs.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetArtist.
        /// </summary>
        public static string SetArtist {
            get {
                return ResourceManager.GetString("SetArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set these volume as the Default.
        /// </summary>
        public static string SetDefaultVolume {
            get {
                return ResourceManager.GetString("SetDefaultVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetDesigner.
        /// </summary>
        public static string SetDes {
            get {
                return ResourceManager.GetString("SetDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTitle.
        /// </summary>
        public static string SetTitle {
            get {
                return ResourceManager.GetString("SetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Volume as Default Setting.
        /// </summary>
        public static string SetToDefaultVolume {
            get {
                return ResourceManager.GetString("SetToDefaultVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Your new chart will use these volume setting as default..
        /// </summary>
        public static string SetVolumeDefaultSuccess {
            get {
                return ResourceManager.GetString("SetVolumeDefaultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimaiWiki.
        /// </summary>
        public static string SimaiWiki {
            get {
                return ResourceManager.GetString("SimaiWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Detection Accuracy must be a number! Please check your input and delete unnecessary characters like space..
        /// </summary>
        public static string SlideAccInputError {
            get {
                return ResourceManager.GetString("SlideAccInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide-Tap Detection Acc:.
        /// </summary>
        public static string SlideAccuracy {
            get {
                return ResourceManager.GetString("SlideAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SlideTapError] &quot;{0}&quot;({1}L,{2}C) may obstructs &quot;{3}&quot;({4}L,{5}C). Interval:{6}ms.
        /// </summary>
        public static string SlideError {
            get {
                return ResourceManager.GetString("SlideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide-Tap Error: when a SLIDE runs into a TAP in &quot;A Area&quot;, it may
        ///accidentally get this TAP triggered.
        ///The accuracy of detection on Slide-Tap Error. Unit: second.
        ///Please DO NOT enter a value less than 0.15, or some of the
        ///wrong notes may be not detected.
        ///An accuracy to 0.2 or higher is recommended if you want to
        ///get the map greater..
        /// </summary>
        public static string SlideTooltip {
            get {
                return ResourceManager.GetString("SlideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booting as software rendering mode..
        /// </summary>
        public static string SoftRender {
            get {
                return ResourceManager.GetString("SoftRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Thread Failure！
        ///Please run the MajdatEdit by &quot;强制软件渲染.bat&quot; in the folder. This may solve the problem..
        /// </summary>
        public static string SoftRenderError {
            get {
                return ResourceManager.GetString("SoftRenderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change these settings, go to &quot;Setting-&gt;Editor Setting&quot;..
        /// </summary>
        public static string SpeedSettingTooltip {
            get {
                return ResourceManager.GetString("SpeedSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Check.
        /// </summary>
        public static string StartCheck {
            get {
                return ResourceManager.GetString("StartCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SyntaxError] &quot;{0}&quot;({1}L,{2}C) fail to analyze，may be a syntax error here..
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextFollow.
        /// </summary>
        public static string TextFollow {
            get {
                return ResourceManager.GetString("TextFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Speed.
        /// </summary>
        public static string TouchSpeed {
            get {
                return ResourceManager.GetString("TouchSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unsaved).
        /// </summary>
        public static string Unsaved {
            get {
                return ResourceManager.GetString("Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3 file that is not 44100Hz may not be supported..
        /// </summary>
        public static string Warn44100Hz {
            get {
                return ResourceManager.GetString("Warn44100Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s This.
        /// </summary>
        public static string WhatsThis {
            get {
                return ResourceManager.GetString("WhatsThis", resourceCulture);
            }
        }
    }
}
